WARNING: No test specified, defaulting to first test defined (_)
TRACE: Initialized test input buffer with data from `/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/fastclarans_output/72b8674b8dc1edb8a927c3a229789e801397bd23.fail`
TRACE: Running: _ from /home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/fastclarans_DeepState_TestHarness.cpp(13)
input starts
EXTERNAL: qs v0.23.5.

rdist values: 8.18711e+299 0.00468189 9.28697e-257 -4.47314e+269 -1.08462e-247 -1.0696e+114 -3.47955e-216 -8.95181e+215 1.38348e-136 6.24605e+181 -4.11368e+80 -nan 2.79008e+291 -2.43673e+290 1.13722e+165 1.24929e+186 -9.06014e-190 1.24372e-163 1.07357e-51 -6.7207e-236 3.93269e-254 -3.45571e+99 8.95779e+89 -1.04429e+114 2.77225e+43 -2.18557e+139 -2.63808e-55 -1.77674e-44
n values: -1184194678
k values: 1318245361
numlocal values: -1315440106
maxneighbor values: 4.71098e+56
seed values: 357367640
input ends
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
ERROR: Failed: _
ERROR: Test case /home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/fastclarans_output/72b8674b8dc1edb8a927c3a229789e801397bd23.fail failed
