WARNING: No test specified, defaulting to first test defined (_)
TRACE: Initialized test input buffer with data from `/home/akhila/fuzzer_packages/fuzzedpackages/scoringRules/inst/testfiles/makeregs_fcC/makeregs_fcC_output/1f30cf7e276e02767f0df79ce146ff41f71b7899.fail`
TRACE: Running: _ from /home/akhila/fuzzer_packages/fuzzedpackages/scoringRules/inst/testfiles/makeregs_fcC/makeregs_fcC_DeepState_TestHarness.cpp(13)
input starts
ydat values:   1.9530e-225  3.6712e+174 -6.0225e+297  -2.4781e-14 -3.6407e+264 -1.0267e+221 -4.9390e-292   1.1883e+83   4.5494e+83  6.1455e-207
  2.6827e+268 -1.4940e+247  7.6874e-208  5.5498e+180 -1.2110e-290 -9.5676e-120 -1.2378e+306 -6.5868e-128  6.8792e+136 -4.0975e-228
  5.9333e-215  2.8911e+289 -1.6463e+219   2.7772e+36  9.3050e-126  -8.4017e-48 -8.7277e-222  4.2706e+243  7.5618e+267  1.4852e-139

EXTERNAL: qs v0.23.5.

p values: 4.58275e+262
input ends

error: Mat::row(): index out of bounds
terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::row(): index out of bounds
ERROR: Failed: _
ERROR: Test case /home/akhila/fuzzer_packages/fuzzedpackages/scoringRules/inst/testfiles/makeregs_fcC/makeregs_fcC_output/1f30cf7e276e02767f0df79ce146ff41f71b7899.fail failed
