WARNING: No test specified, defaulting to first test defined (_)
TRACE: Initialized test input buffer with data from `/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/wasserstein_distance_output/119a337d8687dd2d49dd9c13821bcbbec48f8fd0.fail`
TRACE: Running: _ from /home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/wasserstein_distance_DeepState_TestHarness.cpp(13)
input starts
Missing value
EXTERNAL: qs v0.23.5.

Diag1 values: 3.60909e+224 9.37481e+280 1.27048e-62 4.71376e-48     nan 7.46115e-258 1.41003e-86
1.11742e+83 3.07504e-136 2.13410e-145 1.75062e-260 2.90402e-286 5.01413e+184 1.93644e+180
1.97870e+143 1.01645e-124 2.01769e+47 4.13273e+261 3.56215e-230     nan 1.99326e-62
    nan 1.00679e-73     nan 7.50348e-71 1.43678e-133 29072.6 1.39816e-16

Diag2 values: 4.71727e-75 2.98963e-36 1.44019e-33 2.16906e-76

q values: -1007985803
internal_p values: -4.68831e-154
delta values: 1.11903e+232
initial_eps values: 3.26286e-84
eps_factor values: 3.96693e-30
input ends
terminate called after throwing an instance of 'std::runtime_error'
  what():  Bad q in Wasserstein -1007985803.000000
ERROR: Failed: _
ERROR: Test case /home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/wasserstein_distance_output/119a337d8687dd2d49dd9c13821bcbbec48f8fd0.fail failed
